/*
** reads keyboard for status flags
** scan code and character generated by
** a keystroke.
*/

#include <stdio.h>
#include <dos.h>


main()
{
    unsigned int huge *keyb;
    keyb = 0x0417;
    fflush(stdin);
    _AH = 0x02;
    geninterrupt(0x16);
    printf("\n\nkeyboard flag = %X\n",_AL);
    printf("\n keyb points to %p\n",keyb);
    printf("\n address 417h value = %X",*keyb);
    fflush(stdin);
    _AH = 0x00;
    geninterrupt(0x16);
    printf("\nscan code = %X ASCII code = %X",_AH,_AL);
    *keyb = 0x00;
}